version: '3.8'

services:
  cbk-retail-bonds:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3201:80"
    container_name: cbk-retail-bonds
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro



